

terror_key_dict: dict = {
    6: "Black Marsh</br>The Hole",
    2: "Blood Moor</br>Den of Evil",
    17: "Burial Grounds</br>Crypt</br>Mausoleum",
    33: "Cathedral</br>Catacombs",
    3: "Cold Plains</br>Cave",
    5: "Darkwood</br>Underground Passage",
    28: "Jail</br>Barracks",
    39: "Moo Moo Farm",
    4: "Stony Field",
    20: "Forgotten Tower",
    12: "Pit",
    38: "Tristram",
    65: "Ancient Tunnels",
    74: "Arcane Sanctuary",
    42: "Dry Hills</br>Halls of the Dead",
    43: "Far Oasis",
    44: "Lost City</br>Valley of Snakes</br>Claw Viper Temple",
    47: "Lut Gholein Sewers",
    41: "Stony Tomb</br>Rocky Waste",
    66: "Tal Rasha's Tombs",
    100: "Durance of Hate",
    78: "Flayer Jungle and Dungeon",
    77: "Great Marsh",
    80: "Kurast Bazaar</br>Temples",
    76: "Spider Forest</br>Spider Cavern",
    83: "Travincal",
    108: "Chaos Sanctuary",
    104: "Outer Steppes</br>Plains of Despair",
    106: "City of the Damned</br>River of Flame",
    118: "Ancient's Way</br>Icy Cellar",
    112: "Arreat Plateau</br>Pit of Acheron",
    110: "Bloody Foothills</br>Frigid Highlands</br>Abbadon",
    113: "Crystalline Passage</br>Frozen River",
    115: "Glacial Trail</br>Drifter Cavern",
    121: "Nihlathak's Temple and Halls",
    128: "Worldstone Keep</br>Throne of Destruction</br>Worldstone Chamber",
}
