# Generated by Django 4.1.6 on 2023-02-14 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Guild",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "fasttrade_channels",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fasttrade_set",
                        to="guilds.channel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "terror_channels",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terror_set",
                        to="guilds.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guilds.guild"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TerrorZoneTemplate",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name_en", models.CharField(blank=True, max_length=150, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=150, null=True)),
                ("act", models.CharField(blank=True, max_length=5, null=True)),
                ("immunities_en", models.TextField(blank=True, null=True)),
                ("immunities_ru", models.TextField(blank=True, null=True)),
                ("boss_packs", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "super_uniques",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "sparkly_chests",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guilds.guild"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guilds.roles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Terror Zone Template",
            },
        ),
        migrations.CreateModel(
            name="TerrorZones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="guilds.guild"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="guilds.roles",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guilds.terrorzonetemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="channel",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="guilds.guild"
            ),
        ),
    ]
