# Generated by Django 4.1.6 on 2023-02-16 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channels",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Channels",
                "verbose_name_plural": "Channels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Roles",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TerrorZones",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name_en", models.CharField(blank=True, max_length=150, null=True)),
                ("name_ru", models.CharField(blank=True, max_length=150, null=True)),
                ("act", models.CharField(blank=True, max_length=5, null=True)),
                ("immunities_en", models.TextField(blank=True, null=True)),
                ("immunities_ru", models.TextField(blank=True, null=True)),
                ("boss_packs", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "super_uniques",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "sparkly_chests",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="guilds.roles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terror Zones",
                "verbose_name_plural": "Terror Zones",
                "ordering": ("act", "name_en"),
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "clone_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clone_set",
                        to="guilds.channels",
                    ),
                ),
                (
                    "fasttrade_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fasttrade_set",
                        to="guilds.channels",
                    ),
                ),
                (
                    "terror_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terror_set",
                        to="guilds.channels",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
