# Generated by Django 4.1.6 on 2023-02-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="max_time",
            field=models.IntegerField(default=5),
        ),
    ]
