# Generated by Django 4.1.6 on 2023-02-14 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terrorzonetemplate",
            name="guild",
        ),
        migrations.RemoveField(
            model_name="terrorzonetemplate",
            name="role",
        ),
    ]
