# Generated by Django 4.1.5 on 2023-02-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0002_remove_terrorzonetemplate_guild_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="terrorzones",
            options={
                "verbose_name": "TerrorZones",
                "verbose_name_plural": "TerrorZones",
            },
        ),
        migrations.AlterModelOptions(
            name="terrorzonetemplate",
            options={
                "ordering": ("act", "name_en"),
                "verbose_name": "Terror Zone Template",
            },
        ),
        migrations.AlterField(
            model_name="terrorzones",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="guilds.terrorzonetemplate",
                unique=True,
            ),
        ),
    ]
