# Generated by Django 4.1.6 on 2023-07-23 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0002_alter_channels_name_alter_roles_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roles",
            unique_together={("id", "name")},
        ),
    ]
