# Generated by Django 4.1.6 on 2023-02-16 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0003_alter_settings_max_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="max_time",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(60),
                ],
            ),
        ),
    ]
