# Generated by Django 4.1.5 on 2023-02-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0003_alter_terrorzones_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="terrorzones",
            options={
                "ordering": ("zone__act", "zone"),
                "verbose_name": "TerrorZones",
                "verbose_name_plural": "TerrorZones",
            },
        ),
        migrations.AlterField(
            model_name="terrorzones",
            name="zone",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="guilds.terrorzonetemplate",
            ),
        ),
    ]
