# Generated by Django 4.1.5 on 2023-02-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilds", "0004_alter_terrorzones_options_alter_terrorzones_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrorzones",
            name="zone",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="guilds.terrorzonetemplate",
            ),
        ),
    ]
