# Generated by Django 4.1.6 on 2023-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0005_settings_fasttrade_channel_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="fasttrade_channel_time",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
