# Generated by Django 4.1.6 on 2023-02-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0007_alter_terrorzones_sparkly_chests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrorzones",
            name="key",
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
