# Generated by Django 4.1.6 on 2023-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("discriminator", models.CharField(blank=True, max_length=50)),
                ("bot", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "verbose_name": "DiscordUser",
                "verbose_name_plural": "DiscordUsers",
                "unique_together": {("id", "username")},
            },
        ),
    ]
