# Generated by Django 4.1.6 on 2023-07-18 12:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200)),
                ("discriminator", models.CharField(blank=True, max_length=50)),
                ("bot", models.BooleanField(blank=True, default=False)),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2000, 1, 1, 7, 0, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "DiscordUser",
                "verbose_name_plural": "DiscordUsers",
                "unique_together": {("username", "discriminator")},
            },
        ),
    ]
