# Generated by Django 4.1.6 on 2023-07-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guilds", "0002_alter_channels_name_alter_roles_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="roles",
            field=models.ManyToManyField(to="guilds.roles"),
        ),
    ]
