# Generated by Django 4.1.5 on 2023-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cookies",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
