# Generated by Django 4.1.6 on 2023-07-15 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_discorduser_joined_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="discorduser",
            unique_together={("id", "username", "discriminator")},
        ),
    ]
