# Generated by Django 4.1.6 on 2023-07-15 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_discorduser_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="discorduser",
            unique_together={("username", "discriminator")},
        ),
    ]
